server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: gateway
  config:
    import: "optional:config-serv:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: address
          uri: lb://address
          predicates:
            - Path=/api/employee/**
        - id: bill
          uri: lb://bill
          predicates:
            - Path=/api/department/**
