server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: gateway
  config:
    import: "optional:config-serv:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: address
          uri: lb://address
          predicates:
            - Path=/api/address/**

        - id: bill
          uri: lb://bill
          predicates:
            - Path=/api/bill/**

        - id: category
          uri: lb://category
          predicates:
            - Path=/api/category/**

        - id: customer
          uri: lb://customer
          predicates:
            - Path=/api/customer/**

        - id: food-cart
          uri: lb://food-cart
          predicates:
            - Path=/api/food/**

        - id: item
          uri: lb://item
          predicates:
            - Path=/api/item/**

        - id: order-deatels
          uri: lb://order-deatels
          predicates:
            - Path=/api/order/**

        - id: restaurant
          uri: lb://restaurant
          predicates:
            - Path=/api/restaurant/**

---


