#eureka:
#    client:
#        fetch-register: true
#        register-with-eureka: true
#        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
server:
    port: 7008

spring:
    application:
        name: bill
    config:
        import: "optional:config-serv:http://localhost:8088"
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: raju
        url: jdbc:mysql://localhost:3306/bill
        username: root
    jdbc:
        show-sql: true
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
